'use strict';

const axios = require('axios');
const { generateWAMessageFromContent, proto } = require('@pasqua-baileys/baileys');

module.exports = {
    name: 'nexus',
    aliases: ['portal', 'browse', 'sky'],
    description: 'The Reality Portal — Virtual Browser & Flight Tracking',
    usage: '.nexus',
    category: 'media',

    async execute({ sock, msg, from, args, reply, prefix }) {
        const subCommand = args[0]?.toLowerCase();

        // Main Nexus Menu with Buttons
        if (!subCommand) {
            const buttons = [
                {
                    name: 'quick_reply',
                    buttonParamsJson: JSON.stringify({ display_text: '🌐 Virtual Browser', id: `${prefix}nexus browse` }),
                },
                {
                    name: 'quick_reply',
                    buttonParamsJson: JSON.stringify({ display_text: '✈️ Sky Radar', id: `${prefix}nexus sky` }),
                },
                {
                    name: 'cta_url',
                    buttonParamsJson: JSON.stringify({
                        display_text: '🛰️ Global Live Map',
                        url: 'https://www.flightradar24.com',
                        merchant_url: 'https://www.flightradar24.com',
                    }),
                }
            ];

            const interactiveMessage = {
                body: { text: '🌐 *NEXUS REALITY PORTAL*\n\nWelcome to the Nexus. Choose a gateway to intercept global data streams or render the digital world.' },
                footer: { text: 'SUKUNA MD · Nexus Engine' },
                header: {
                    title: '✦ NEXUS PORTAL ✦',
                    subtitle: 'Reality Interception System',
                    hasMediaAttachment: false,
                },
                nativeFlowMessage: {
                    buttons,
                    messageParamsJson: '',
                },
            };

            const wrapped = generateWAMessageFromContent(
                from,
                {
                    viewOnceMessage: {
                        message: {
                            messageContextInfo: { deviceListMetadataVersion: 2, deviceListMetadata: {} },
                            interactiveMessage: proto.Message.InteractiveMessage.fromObject(interactiveMessage),
                        },
                    },
                },
                { userJid: sock.user?.id, quoted: msg }
            );

            await sock.relayMessage(from, wrapped.message, { messageId: wrapped.key.id });
            return;
        }

        if (subCommand === 'browse') {
            const url = args[1];
            if (!url) return reply('❌ Please provide a URL after the command (e.g., .nexus browse google.com)');
            
            const targetUrl = url.startsWith('http') ? url : `https://${url}`;
            await sock.sendMessage(from, { react: { text: '🌐', key: msg.key } });
            await reply('🌀 *Opening Reality Portal...*');

            try {
                // Using Microlink with peak rendering options
                const screenshotUrl = `https://api.microlink.io/?url=${encodeURIComponent(targetUrl)}&screenshot=true&meta=false&embed=screenshot.url&waitFor=3000&colorScheme=dark`;
                
                await sock.sendMessage(from, {
                    image: { url: screenshotUrl },
                    caption: `🌐 *NEXUS BROWSER*\n\n*URL:* ${targetUrl}\n*Status:* Live Rendered\n\n_Generated by Nexus Engine_`
                }, { quoted: msg });
                
                await sock.sendMessage(from, { react: { text: '✨', key: msg.key } });
            } catch (e) {
                console.error(e);
                reply('❌ Portal collapsed: Failed to render the website.');
            }
        } 
        else if (subCommand === 'sky' || subCommand === 'flight') {
            await sock.sendMessage(from, { react: { text: '✈️', key: msg.key } });
            await reply('🛰️ *Intercepting Satellite Data...*');

            try {
                const res = await axios.get('https://opensky-network.org/api/states/all', { timeout: 15000 });
                const states = res.data?.states || [];
                
                if (states.length === 0) return reply('❌ No active flight data found in the atmosphere.');

                const topFlights = states.slice(0, 10);
                
                let report = `🛰️ *GOD-EYE SURVEILLANCE*\n\n`;
                report += `Total Flights Tracked: ${states.length}\n\n`;
                
                topFlights.forEach((f, i) => {
                    const callsign = f[1] ? f[1].trim() : 'UNKNOWN';
                    const country = f[2] || 'Unknown';
                    const altitude = f[7] ? `${Math.round(f[7])}m` : 'N/A';
                    const velocity = f[9] ? `${Math.round(f[9] * 3.6)}km/h` : 'N/A';
                    
                    report += `${i + 1}. ✈️ *${callsign}*\n`;
                    report += `   🌍 Origin: ${country}\n`;
                    report += `   📏 Altitude: ${altitude}\n`;
                    report += `   🚀 Speed: ${velocity}\n\n`;
                });
                
                report += `_Showing top 10 global active flights._`;

                await sock.sendMessage(from, {
                    text: report,
                    contextInfo: {
                        externalAdReply: {
                            title: 'LIVE FLIGHT RADAR',
                            body: 'Global Air Traffic Surveillance',
                            thumbnailUrl: 'https://cdn-icons-png.flaticon.com/512/784/784850.png',
                            sourceUrl: 'https://opensky-network.org',
                            mediaType: 1
                        }
                    }
                }, { quoted: msg });
                
                await sock.sendMessage(from, { react: { text: '📡', key: msg.key } });
            } catch (e) {
                console.error(e);
                reply('❌ Satellite link lost: Failed to retrieve flight data.');
            }
        }
        else {
            reply(`❌ Unknown Nexus gateway. Use \`${prefix}nexus\` to see options.`);
        }
    }
};
