services:
  - type: web
    name: sukuna-md
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PAIR_SITE_URL
        value: https://pair-site-wmte.onrender.com
      - key: PAIR_NUMBER
        sync: false
      - key: SESSION_ID
        sync: false
      - key: OWNER_NUMBER
        sync: false
