/**
 * Shared textmaker helper.
 *
 * The old mumaker/ephoto360 scraper depended on a third-party HTML flow that
 * changes frequently and can fail for every textmaker command at once. This
 * implementation uses Placehold.co's public, keyless PNG endpoint instead.
 * It is deterministic, has no API key, and returns a direct image URL that
 * WhatsApp can fetch.
 */
'use strict';

const channelInfo = {
    forwardingScore: 1,
    isForwarded: true,
    forwardedNewsletterMessageInfo: {
        newsletterJid: '120363424109748354@newsletter',
        newsletterName: 'Sukuna MD Pasqua tech',
        serverMessageId: -1,
    },
};

const messageTemplates = {
    error: (text) => ({ text, contextInfo: channelInfo }),
    success: (imageUrl, caption) => ({
        image: { url: imageUrl },
        caption: caption || 'GENERATED BY SUKUNA MD',
        contextInfo: channelInfo,
    }),
};

function makeKeylessTextImageUrl(text) {
    const cleanText = String(text || '').trim().slice(0, 120);
    if (!cleanText) throw new Error('Text is required');
    return `https://placehold.co/1200x630/111827/FFFFFF/png?text=${encodeURIComponent(cleanText)}`;
}

async function fetchEphoto(_legacyUrl, text) {
    // Keep the old function name and command signatures for compatibility;
    // the legacy ephoto URL is intentionally ignored.
    return makeKeylessTextImageUrl(text);
}

function makeTextmakerCommand({ name, ephotoUrl, label, emoji = '✨', aliases = [] }) {
    return {
        name,
        aliases,
        description: `${label} text effect`,
        category: 'textmaker',
        async execute({ sock, msg, from, reply, args }) {
            if (!args.length) {
                return sock.sendMessage(
                    from,
                    messageTemplates.error(
                        `${emoji} *${label}*\n\nUsage: .${name} <text>\nExample: .${name} SUKUNA`
                    ),
                    { quoted: msg }
                );
            }
            const text = args.join(' ').trim().slice(0, 120);
            try {
                await sock.sendMessage(from, { react: { text: '⏳', key: msg.key } });
                const imageUrl = await fetchEphoto(ephotoUrl, text);
                const caption = `${emoji} *${label}* — ${text}\n\n> SUKUNA MD`;
                await sock.sendMessage(
                    from,
                    messageTemplates.success(imageUrl, caption),
                    { quoted: msg }
                );
                await sock.sendMessage(from, { react: { text: '✅', key: msg.key } });
            } catch (err) {
                console.error(`[${name}] error:`, err.message);
                try { await sock.sendMessage(from, { react: { text: '❌', key: msg.key } }); } catch {}
                await sock.sendMessage(
                    from,
                    messageTemplates.error(`❌ ${label} failed: ${err.message}`),
                    { quoted: msg }
                );
            }
        },
    };
}

module.exports = { fetchEphoto, makeTextmakerCommand, messageTemplates, channelInfo, makeKeylessTextImageUrl };
