/**
 * Textmaker helper.
 *
 * Primary provider: Mumaker/ephoto360.
 * Fallback provider: free-textmaker-alpha/TextPro.
 *
 * Both providers return a real generated image URL. Canvas rendering is not
 * used as a textmaker fallback because it does not produce the requested
 * TextPro/effect artwork.
 */
'use strict';

const mumaker = require('mumaker');
let AlphaAPI = null;
try {
    AlphaAPI = require('free-textmaker-alpha');
} catch (error) {
    console.error('[TEXTMAKER] free-textmaker-alpha unavailable:', error.message);
}

const DEFAULT_TEXT_PRO_URL = process.env.TEXTMAKER_TEXTPRO_URL ||
    'https://textpro.me/create-neon-devil-wings-text-effect-online-free-1014.html';

// SUKUNA MD channel pill — attached to every textmaker reply.
const channelInfo = {
    forwardingScore: 1,
    isForwarded: true,
    forwardedNewsletterMessageInfo: {
        newsletterJid: '120363424109748354@newsletter',
        newsletterName: 'Sukuna MD Pasqua tech',
        serverMessageId: -1,
    },
};

const messageTemplates = {
    error: (text) => ({ text, contextInfo: channelInfo }),
    success: (imageUrl, caption) => ({
        image: { url: imageUrl },
        caption: caption || 'GENERATED BY SUKUNA MD',
        contextInfo: channelInfo,
    }),
};

function extractImageUrl(result) {
    if (typeof result === 'string') return result;
    if (!result || typeof result !== 'object') return '';
    return result.image || result.url || result.link || result.src || '';
}

function assertImageUrl(value, provider) {
    const imageUrl = extractImageUrl(value);
    if (!imageUrl || typeof imageUrl !== 'string') {
        throw new Error(`${provider} returned no image URL`);
    }
    if (!/^https?:\/\//i.test(imageUrl)) {
        throw new Error(`${provider} returned an invalid image URL`);
    }
    return imageUrl;
}

async function fetchEphoto(url, text) {
    const result = await mumaker.ephoto(url, text);
    return assertImageUrl(result, 'Mumaker');
}

async function fetchTextPro(url, text) {
    if (!AlphaAPI || typeof AlphaAPI.textpro !== 'function') {
        throw new Error('TextPro fallback is unavailable');
    }
    const result = await AlphaAPI.textpro(url || DEFAULT_TEXT_PRO_URL, text);
    return assertImageUrl(result, 'TextPro');
}

async function fetchTextmakerImage({ ephotoUrl, textproUrl, text }) {
    const failures = [];
    try {
        return { imageUrl: await fetchEphoto(ephotoUrl, text), provider: 'Mumaker' };
    } catch (error) {
        failures.push(`Mumaker: ${error.message}`);
    }

    try {
        return { imageUrl: await fetchTextPro(textproUrl || DEFAULT_TEXT_PRO_URL, text), provider: 'TextPro' };
    } catch (error) {
        failures.push(`TextPro: ${error.message}`);
    }

    const combined = failures.join(' | ');
    throw new Error(combined || 'No textmaker provider is available');
}

function makeTextmakerCommand({ name, ephotoUrl, textproUrl = DEFAULT_TEXT_PRO_URL, label, emoji = '✨', aliases = [] }) {
    return {
        name,
        aliases,
        description: `${label} text effect`,
        category: 'textmaker',
        async execute({ sock, msg, from, reply, args }) {
            if (!args.length) {
                return sock.sendMessage(
                    from,
                    messageTemplates.error(
                        `${emoji} *${label}*\n\nUsage: .${name} <text>\nExample: .${name} SUKUNA`
                    ),
                    { quoted: msg }
                );
            }

            const text = args.join(' ').trim().slice(0, 60);
            try {
                await sock.sendMessage(from, { react: { text: '⏳', key: msg.key } });
                const { imageUrl, provider } = await fetchTextmakerImage({ ephotoUrl, textproUrl, text });
                const caption = `${emoji} *${label}* — ${text}\n\n> SUKUNA MD`;
                await sock.sendMessage(
                    from,
                    messageTemplates.success(imageUrl, caption),
                    { quoted: msg }
                );
                await sock.sendMessage(from, { react: { text: '✅', key: msg.key } });
                return provider;
            } catch (error) {
                console.error(`[${name}] providers failed:`, error.message);
                try { await sock.sendMessage(from, { react: { text: '❌', key: msg.key } }); } catch (_) {}
                await sock.sendMessage(
                    from,
                    messageTemplates.error(`❌ ${label} is temporarily unavailable. Please try again in a moment.`),
                    { quoted: msg }
                );
                return null;
            }
        },
    };
}

module.exports = {
    DEFAULT_TEXT_PRO_URL,
    fetchEphoto,
    fetchTextPro,
    fetchTextmakerImage,
    makeTextmakerCommand,
    messageTemplates,
    channelInfo,
};
