/**
 * Stable text-maker renderer with a distinct preset for each command.
 * The legacy ePhoto URL remains accepted for compatibility, but no brittle
 * scraper is used because ePhoto pages change and are often anti-bot protected.
 */
'use strict';

const channelInfo = {
    forwardingScore: 1,
    isForwarded: true,
    forwardedNewsletterMessageInfo: {
        newsletterJid: '120363424109748354@newsletter',
        newsletterName: 'Sukuna MD Pasqua tech',
        serverMessageId: -1,
    },
};

const messageTemplates = {
    error: (text) => ({ text, contextInfo: channelInfo }),
    success: (imageUrl, caption) => ({
        image: { url: imageUrl },
        caption: caption || 'GENERATED BY SUKUNA MD',
        contextInfo: channelInfo,
    }),
};

const STYLE_PRESETS = {
    glitch: { background: '0b0614', foreground: 'f8f7ff', accent: 'ff2bd6', prefix: '╱╲  GLITCH  ╱╲', suffix: '▌▐  SYSTEM ERROR  ▌▐' },
    gradient: { background: '4c1d95', foreground: 'fff7ed', accent: 'fbbf24', prefix: '✦  DREAM COLORS  ✦', suffix: '紫  •  GOLD  •  VIOLET' },
    underwater: { background: '06324a', foreground: 'e0f2fe', accent: '67e8f9', prefix: '≈  DEEP BLUE  ≈', suffix: '｡ﾟ･  BENEATH THE WAVES  ･ﾟ｡' },
    write: { background: '1f2937', foreground: 'fef3c7', accent: 'f59e0b', prefix: '✒  SIGNATURE  ✒', suffix: '— handwritten by SUKUNA —' },
    glow: { background: '17103b', foreground: 'fff7ed', accent: 'a78bfa', prefix: '✦  LUMINOUS GLOW  ✦', suffix: 'LIGHT UP THE NIGHT' },
    clouds: { background: '8ecae6', foreground: 'ffffff', accent: '023047', prefix: '☁  ABOVE THE CLOUDS  ☁', suffix: 'FLOAT • DREAM • CREATE' },
    paint: { background: '7f1d1d', foreground: 'fff7ed', accent: 'fb7185', prefix: '🎨  COLOR SPLASH  🎨', suffix: 'MADE TO STAND OUT' },
    neon: { background: '12051f', foreground: 'f0abfc', accent: '22d3ee', prefix: '▰  NEON DISTRICT  ▰', suffix: 'BRIGHTER THAN MIDNIGHT' },
    devil: { background: '240000', foreground: 'fee2e2', accent: 'ef4444', prefix: '☠  NEON DEVIL  ☠', suffix: 'ENTER THE DARK SIDE' },
    matrix: { background: '031a0b', foreground: '86efac', accent: '22c55e', prefix: '01  MATRIX  10', suffix: 'SYSTEM ONLINE' },
    sand: { background: 'c08457', foreground: 'fff7ed', accent: 'fef3c7', prefix: '☀  SUMMER SANDS  ☀', suffix: 'WRITTEN BY THE TIDE' },
    cinema: { background: '111827', foreground: 'fef3c7', accent: 'fbbf24', prefix: '★  1917 CINEMA  ★', suffix: 'A STORY IN EVERY LETTER' },
};

function cleanText(text) {
    return String(text || '').replace(/[\r\n]+/g, ' ').replace(/[<>]/g, '').trim().slice(0, 90);
}

function normalizeStyle(style) {
    return STYLE_PRESETS[style] || STYLE_PRESETS.gradient;
}

function makeKeylessTextImageUrl(text, style = 'gradient') {
    const clean = cleanText(text);
    if (!clean) throw new Error('Text is required');
    const preset = normalizeStyle(style);
    const lines = [preset.prefix, clean, preset.suffix].join('\n');
    const params = new URLSearchParams({ text: lines, font: 'bold' });
    return `https://placehold.co/1200x630/${preset.background}/${preset.foreground}/png?${params.toString()}`;
}

async function fetchEphoto(_legacyUrl, text, style = 'gradient') {
    return makeKeylessTextImageUrl(text, style);
}

function makeTextmakerCommand({ name, ephotoUrl, label, emoji = '✨', aliases = [], style }) {
    const selectedStyle = style || name.replace(/text$/i, '').toLowerCase();
    return {
        name,
        aliases,
        description: `${label} text effect with a unique ${selectedStyle} design`,
        category: 'textmaker',
        async execute({ sock, msg, from, args }) {
            if (!args.length) {
                return sock.sendMessage(from, messageTemplates.error(
                    `${emoji} *${label}*\n\nUsage: .${name} <text>\nExample: .${name} SUKUNA`
                ), { quoted: msg });
            }
            const text = cleanText(args.join(' '));
            try {
                await sock.sendMessage(from, { react: { text: '⏳', key: msg.key } });
                const imageUrl = await fetchEphoto(ephotoUrl, text, selectedStyle);
                const caption = `${emoji} *${label}*\n╰─ ${text}\n\n> SUKUNA MD • ${selectedStyle.toUpperCase()} EDITION`;
                await sock.sendMessage(from, messageTemplates.success(imageUrl, caption), { quoted: msg });
                await sock.sendMessage(from, { react: { text: '✅', key: msg.key } });
            } catch (err) {
                console.error(`[${name}] error:`, err.message);
                try { await sock.sendMessage(from, { react: { text: '❌', key: msg.key } }); } catch {}
                await sock.sendMessage(from, messageTemplates.error(`❌ ${label} failed: ${err.message}`), { quoted: msg });
            }
        },
    };
}

module.exports = { fetchEphoto, makeTextmakerCommand, messageTemplates, channelInfo, makeKeylessTextImageUrl, STYLE_PRESETS };
module.exports._private = { cleanText, normalizeStyle };
