'use strict';

const { sendRichHtml } = require('./genaiRich');


function matrixHtml() {
    return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>
*{box-sizing:border-box}html,body{margin:0;background:transparent;font-family:Arial,sans-serif}body{padding:6px;background:radial-gradient(circle at 50% 0%,#073b2b,#020907 75%)}.card{padding:12px;border:2px solid #48ff9b;border-radius:20px;background:linear-gradient(145deg,#061b14,#092b20 55%,#020907);color:#dffff0;box-shadow:inset 0 0 0 3px #0d4a32,0 8px 20px #000b}.title{text-align:center;color:#d4ffe8;font:bold 23px Arial Black,Arial,sans-serif;letter-spacing:2px;text-shadow:0 0 12px #48ff9b}.sub{text-align:center;margin:2px 0 8px;color:#82caa8;font:10px monospace}.hud{display:flex;justify-content:space-between;margin:8px 0;padding:8px;border:1px solid #48ff9b66;border-radius:9px;background:#020b07;color:#a8d9bd;font:10px monospace}.hud b{color:#48ff9b;font-size:13px}.boardWrap{position:relative}.board{display:grid;grid-template-columns:repeat(16,1fr);gap:1px;padding:6px;border:2px solid #2b9e65;border-radius:12px;background:#000}.cell{aspect-ratio:1;background:#03140d;box-shadow:inset 0 0 0 1px #0b2a1b}.ship{background:#48ff9b;box-shadow:0 0 7px #48ff9b}.enemy{background:#ff466b;border-radius:50%;box-shadow:0 0 6px #ff466b}.bullet{background:#fff8b0;box-shadow:0 0 7px #fff8b0}.message{height:34px;margin:8px 0;display:grid;place-items:center;border:1px solid #2b8c54;border-radius:8px;background:#031008;color:#bcffc2;font:bold 11px monospace}.controls{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;max-width:280px;margin:auto}.controls button{height:40px;border:2px solid #238d50;border-radius:10px;color:#d8ffe0;background:linear-gradient(#155e35,#07341c);font-size:15px;font-weight:900}.controls button:active{transform:scale(.92)}.hint{text-align:center;margin-top:7px;color:#7fc58d;font:9px monospace}.restart{display:block;width:130px;margin:8px auto 0;height:35px;border:1px solid #238d50;border-radius:9px;color:#d8ffe0;background:#0b4226;font-weight:900}
</style></head><body><div class="card"><div class="title">MATRIX</div><div class="sub">NEON SPACE DEFENDER</div><div class="hud"><span>SCORE <b id="score">0</b></span><span>LEVEL <b id="level">1</b></span><span>HP <b id="hp">3</b></span></div><div class="boardWrap"><div class="board" id="board"></div></div><div class="message" id="message">Tap START to launch</div><div class="controls"><button id="left">◀</button><button id="fire">FIRE</button><button id="right">▶</button></div><button class="restart" id="restart">START GAME</button><div class="hint">Shoot the falling objects before they reach your ship</div></div><script>(function(){var W=16,H=20,board=document.getElementById('board'),message=document.getElementById('message'),scoreEl=document.getElementById('score'),levelEl=document.getElementById('level'),hpEl=document.getElementById('hp'),cells=[],ship={x:8,y:18},enemies=[],bullets=[],timer=null,running=false,score=0,hp=3,level=1,tick=0;for(var i=0;i<W*H;i++){var c=document.createElement('div');c.className='cell';board.appendChild(c);cells.push(c)}function idx(x,y){return y*W+x}function reset(){clearInterval(timer);ship={x:8,y:18};enemies=[];bullets=[];score=0;hp=3;level=1;tick=0;running=true;message.textContent='Running — fire at the incoming objects';document.getElementById('restart').textContent='RESTART';draw();timer=setInterval(step,180)}function draw(){cells.forEach(function(c){c.className='cell'});if(ship.y>=0)cells[idx(ship.x,ship.y)].className='cell ship';enemies.forEach(function(e){if(e.y>=0&&e.y<H)cells[idx(e.x,e.y)].className='cell enemy'});bullets.forEach(function(b){if(b.y>=0&&b.y<H)cells[idx(b.x,b.y)].className='cell bullet'});scoreEl.textContent=score;levelEl.textContent=level;hpEl.textContent=hp}function spawn(){enemies.push({x:Math.floor(Math.random()*W),y:0})}function fire(){if(!running)return;bullets.push({x:ship.x,y:ship.y-1})}function move(dx){if(running)ship.x=Math.max(0,Math.min(W-1,ship.x+dx));draw()}function step(){if(!running)return;tick++;if(tick%4===0)spawn();bullets.forEach(function(b){b.y--});enemies.forEach(function(e){e.y++});bullets.forEach(function(b){enemies.forEach(function(e){if(e.y>=0&&b.x===e.x&&b.y===e.y){e.dead=true;b.dead=true;score+=10;level=1+Math.floor(score/100)}})});bullets=bullets.filter(function(b){return !b.dead&&b.y>=0});enemies=enemies.filter(function(e){if(e.dead)return false;if(e.y>=ship.y){hp--;if(hp<=0){running=false;clearInterval(timer);message.textContent='Core destroyed — tap Restart';return false}return false}return true});draw()}document.getElementById('left').onclick=function(){move(-1)};document.getElementById('right').onclick=function(){move(1)};document.getElementById('fire').onclick=fire;document.getElementById('restart').onclick=reset;document.addEventListener('keydown',function(e){if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);if(e.code==='Space')fire()});draw()})();</script></body></html>`;
}

function arcadeHtml(game) {
    if (game === 'matrix') return matrixHtml();
    const configs = {
        matrix: { title: 'MATRIX', subtitle: 'NEON SPACE DEFENDER', accent: '#48ff9b', controls: '<button id="move">◀ DRAG SHIP ▶</button><button id="action">AUTO FIRE: OFF</button>', hud: 'SCORE <b id="score">0</b><span>LV <b id="level">1</b></span><span>HP <b id="hp">3</b></span>', hint: 'Drag the ship left and right · Fire at incoming objects' },
        doom: { title: 'DOOM', subtitle: 'RED CORRIDOR RAID', accent: '#ff334f', controls: '<div class="dpad"><button data-dir="up">▲</button><button data-dir="left">◀</button><button data-dir="down">▼</button><button data-dir="right">▶</button></div><button id="action">FIRE</button>', hud: 'HEALTH <b id="health">100</b><span>LEVEL <b id="level">1</b></span><span>KILLS <b id="kills">0/4</b></span>', hint: 'Use the D-pad to move · Fire to attack' },
        vampire: { title: 'VAMPIRE', subtitle: 'NIGHT SWARM SURVIVAL', accent: '#ffcf4a', controls: '<div class="dpad"><button data-dir="up">▲</button><button data-dir="left">◀</button><button data-dir="down">▼</button><button data-dir="right">▶</button></div><button id="action">⚔ SHOOT</button>', hud: 'HP <b id="health">100</b><span>LV <b id="level">1</b></span><span>KILLS <b id="kills">0</b></span>', hint: 'Move through the field · Shoot the swarm · Collect gems' },
        cyber: { title: 'CYBER', subtitle: 'NEON CITY RUNNER', accent: '#6cf6ff', controls: '<button id="jump">JUMP</button><button id="action">SHOOT</button>', hud: 'DIST <b id="distance">0</b><span>CHIPS <b id="chips">0</b></span><span>HP <b id="hp">3</b></span>', hint: 'Jump over barriers · Shoot them · Collect chips' },
    };
    const cfg = configs[game] || configs.matrix;
    const clientScript = String.raw`(function(){
'use strict';
var GAME='__GAME__', canvas=document.getElementById('game'), ctx=canvas.getContext('2d'), overlay=document.getElementById('overlay'), start=document.getElementById('start'), action=document.getElementById('action'), accent='__ACCENT__';
var running=false, dragging=false, last=0;
var state={score:0,level:1,hp:3,health:100,kills:0,distance:0,chips:0,time:0,x:160,y:345,dy:0,bullets:[],enemies:[],gems:[],obstacles:[],auto:false};
function el(id){return document.getElementById(id)} function set(id,v){var n=el(id);if(n)n.textContent=v}
function reset(){state={score:0,level:1,hp:3,health:100,kills:0,distance:0,chips:0,time:0,x:160,y:345,dy:0,bullets:[],enemies:[],gems:[],obstacles:[],auto:false};running=true;dragging=false;overlay.classList.add('hide');start.textContent='START GAME';seed();last=performance.now();requestAnimationFrame(loop)}
function seed(){var i;for(i=0;i<8;i++)state.enemies.push({x:22+Math.random()*276,y:35+Math.random()*170,w:16,h:16,life:true});for(i=0;i<7;i++)state.gems.push({x:20+Math.random()*280,y:55+Math.random()*260,got:false});for(i=0;i<7;i++)state.obstacles.push({x:360+i*115,y:365,w:26,h:38,chip:i%2===0,life:true})}
function text(t,x,y,size,color){ctx.fillStyle=color||'#fff';ctx.font=(size||12)+'px monospace';ctx.fillText(t,x,y)}
function clear(){ctx.fillStyle=GAME==='doom'?'#180307':GAME==='vampire'?'#071c13':GAME==='cyber'?'#071323':'#02120e';ctx.fillRect(0,0,320,400);ctx.strokeStyle=accent+'22';ctx.lineWidth=1;for(var x=0;x<320;x+=20){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,400);ctx.stroke()}for(var y=0;y<400;y+=20){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(320,y);ctx.stroke()}}
function formatTime(t){var s=Math.floor(t),m=Math.floor(s/60),r=s%60;return String(m).padStart(2,'0')+':'+String(r).padStart(2,'0')}
function hud(){set('score',state.score);set('level',state.level);set('hp',state.hp);set('health',Math.max(0,Math.floor(state.health)));set('kills',GAME==='doom'?state.kills+'/4':state.kills);set('distance',Math.floor(state.distance));set('chips',state.chips);set('timer',formatTime(state.time))}
function drawMatrix(){for(var i=0;i<20;i++){ctx.fillStyle='#ffffff55';ctx.fillRect((i*71+state.time*24)%320,(i*43)%250,2,2)}ctx.fillStyle=accent;ctx.beginPath();ctx.moveTo(state.x,342);ctx.lineTo(state.x-15,374);ctx.lineTo(state.x+15,374);ctx.closePath();ctx.fill();ctx.fillStyle='#e8fffb';state.bullets.forEach(function(b){ctx.fillRect(b.x-2,b.y,4,14)});state.enemies.forEach(function(e){if(!e.life)return;ctx.fillStyle='#ff4a64';ctx.save();ctx.translate(e.x,e.y);ctx.rotate(Math.PI/4);ctx.fillRect(-9,-9,18,18);ctx.restore()});text('INCOMING OBJECTS // SHOOT TO SURVIVE',10,390,9,accent)}
function drawDoom(){ctx.fillStyle='#420b14';ctx.fillRect(25,70,270,250);ctx.fillStyle='#761321';ctx.fillRect(25,70,55,250);ctx.fillRect(240,70,55,250);ctx.fillStyle='#a3242d';ctx.fillRect(80,70,160,8);ctx.fillStyle='#25060b';ctx.fillRect(95,105,130,190);ctx.fillStyle='#e7c0a5';ctx.fillRect(state.x-5,325,10,35);ctx.fillStyle='#6b7688';ctx.fillRect(state.x-25,350,50,13);ctx.fillStyle='#ff334f';state.enemies.slice(0,4).forEach(function(e){if(e.life){ctx.fillRect(e.x-8,e.y-10,16,20);ctx.fillRect(e.x-13,e.y-4,26,8)}});text('LEVEL 1 // RED ZONE',88,45,10,'#ff9caa')}
function drawVampire(){ctx.fillStyle='#0e402b';ctx.fillRect(12,28,296,350);for(var i=0;i<12;i++){ctx.fillStyle='#20724a';ctx.beginPath();ctx.arc((i*47+15)%300+10,(i*71)%330+35,7,0,7);ctx.fill()}state.gems.forEach(function(g){if(!g.got){ctx.fillStyle='#ffcf4a';ctx.beginPath();ctx.arc(g.x,g.y,5,0,7);ctx.fill()}});state.bullets.forEach(function(b){ctx.fillStyle='#fff1a6';ctx.beginPath();ctx.arc(b.x,b.y,3,0,7);ctx.fill()});state.enemies.forEach(function(e){if(e.life){ctx.fillStyle='#e53955';ctx.beginPath();ctx.arc(e.x,e.y,9,0,7);ctx.fill();ctx.fillStyle='#ffb3bc';ctx.fillRect(e.x-3,e.y-2,2,2);ctx.fillRect(e.x+2,e.y-2,2,2)}});ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(state.x,state.y,11,0,7);ctx.fill();ctx.fillStyle='#7137ff';ctx.fillRect(state.x-3,state.y-15,6,8);text('NIGHT '+formatTime(state.time),116,18,10,'#ffcf4a')}
function drawCyber(){ctx.fillStyle='#0c1d34';ctx.fillRect(0,290,320,110);for(var i=0;i<12;i++){var bx=(i*38-(state.distance*2)%38);ctx.fillStyle=i%2?'#14395a':'#102d4a';ctx.fillRect(bx,180+(i%4)*20,30,220);ctx.fillStyle='#6cf6ff';ctx.fillRect(bx+7,205+(i%4)*20,4,4)}ctx.fillStyle='#263b55';ctx.fillRect(0,365,320,35);ctx.fillStyle='#6cf6ff';ctx.fillRect(0,365,320,2);ctx.fillStyle='#ff5c8a';ctx.fillRect(state.x-10,state.y-22,20,22);ctx.fillStyle='#ffe1ed';ctx.fillRect(state.x-5,state.y-30,10,9);state.bullets.forEach(function(b){ctx.fillStyle='#fff36c';ctx.fillRect(b.x,b.y,11,3)});state.obstacles.forEach(function(o){if(o.life&&o.x>-30&&o.x<340){ctx.fillStyle='#ff3e65';ctx.fillRect(o.x,o.y-o.h,o.w,o.h);if(o.chip){ctx.fillStyle='#ffd34f';ctx.beginPath();ctx.arc(o.x+12,o.y-o.h-13,5,0,7);ctx.fill()}}})}
function move(dx,dy){state.x=Math.max(20,Math.min(300,state.x+dx));state.y=Math.max(45,Math.min(345,state.y+dy))}
function fire(){if(!running)return;if(GAME==='matrix'){state.bullets.push({x:state.x,y:330,vy:-290});return}if(GAME==='doom'){var target=state.enemies.find(function(e){return e.life&&Math.abs(e.x-state.x)<95});if(target){target.life=false;state.kills++;if(state.kills>=4)end('LEVEL CLEAR')}return}if(GAME==='vampire'){var target=state.enemies.filter(function(e){return e.life}).sort(function(a,b){return Math.hypot(a.x-state.x,a.y-state.y)-Math.hypot(b.x-state.x,b.y-state.y)})[0];var tx=target?target.x:state.x,ty=target?target.y:state.y;var dx=tx-state.x,dy=ty-state.y,len=Math.hypot(dx,dy)||1;state.bullets.push({x:state.x,y:state.y,vx:dx/len*260,vy:dy/len*260});return}if(GAME==='cyber'){state.bullets.push({x:state.x+12,y:state.y-14,vx:330,vy:0})}}
function jump(){if(running&&state.y>=344){state.dy=-380}}
function respawnMatrix(e){e.life=true;e.y=25;e.x=20+Math.random()*280}
function end(message){running=false;overlay.classList.remove('hide');start.textContent=message+' · RESTART'}
function update(dt){state.time+=dt;if(GAME==='matrix'){if(state.auto||Math.random()<dt*.8)fire();state.bullets.forEach(function(b){b.y+=b.vy*dt});state.bullets=state.bullets.filter(function(b){return b.y>10});state.enemies.forEach(function(e){if(!e.life)return;e.y+=(55+state.level*4)*dt;if(e.y>385){e.life=false;state.hp--;setTimeout(function(){if(running)respawnMatrix(e)},250);if(state.hp<=0)end('CORE DESTROYED')}});state.bullets.forEach(function(b){state.enemies.forEach(function(e){if(e.life&&Math.abs(b.x-e.x)<16&&Math.abs(b.y-e.y)<18){e.life=false;state.score+=10;setTimeout(function(){if(running)respawnMatrix(e)},180)}})});state.level=1+Math.floor(state.score/100)}
if(GAME==='doom'){state.enemies.forEach(function(e){if(!e.life)return;e.x+=(state.x-e.x)*dt*.12;if(Math.random()<dt*.2){state.health-=2;if(state.health<=0)end('YOU DIED')}});}

if(GAME==='vampire'){state.bullets.forEach(function(b){b.x+=b.vx*dt;b.y+=b.vy*dt});state.bullets=state.bullets.filter(function(b){return b.x>-10&&b.x<330&&b.y>20&&b.y<390});state.enemies.forEach(function(e){if(!e.life)return;e.x+=(state.x-e.x)*dt*.22;e.y+=(state.y-e.y)*dt*.22;if(Math.hypot(e.x-state.x,e.y-state.y)<18){state.health-=16*dt;if(state.health<=0)end('NIGHT CLAIMED YOU')}});state.bullets.forEach(function(b){state.enemies.forEach(function(e){if(e.life&&Math.hypot(b.x-e.x,b.y-e.y)<15){e.life=false;state.kills++;state.score+=10;setTimeout(function(){if(running){e.life=true;e.x=20+Math.random()*280;e.y=35+Math.random()*180}},350)}})});state.gems.forEach(function(g){if(!g.got&&Math.hypot(g.x-state.x,g.y-state.y)<18){g.got=true;state.score+=10;state.level=1+Math.floor(state.score/50)}})}
if(GAME==='cyber'){state.distance+=dt*18;state.dy+=900*dt;state.y+=state.dy*dt;if(state.y>345){state.y=345;state.dy=0}state.bullets.forEach(function(b){b.x+=b.vx*dt});state.bullets=state.bullets.filter(function(b){return b.x<340});state.obstacles.forEach(function(o){if(!o.life)return;o.x-=dt*110;if(o.x<-35){o.x=340+Math.random()*70;o.life=true;o.chip=Math.random()>.35}state.bullets.forEach(function(b){if(o.life&&b.x<o.x+o.w&&b.x+11>o.x&&b.y>o.y-o.h&&b.y<o.y){o.life=false;state.score+=10;if(o.chip)state.chips++}});if(o.life&&o.x<state.x+12&&o.x+o.w>state.x-12&&state.y>o.y-o.h+8){state.hp--;o.life=false;if(state.hp<=0)end('RUN ENDED')}})} }
function draw(){clear();if(GAME==='matrix')drawMatrix();if(GAME==='doom')drawDoom();if(GAME==='vampire')drawVampire();if(GAME==='cyber')drawCyber();hud()}
function loop(ts){if(!running)return;var dt=Math.min(.05,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop)}
function pointerPosition(e){var r=canvas.getBoundingClientRect();return Math.max(18,Math.min(302,(e.clientX-r.left)*320/r.width))}
function controls(){if(GAME==='matrix'){canvas.addEventListener('pointerdown',function(e){dragging=true;canvas.setPointerCapture(e.pointerId);state.x=pointerPosition(e)});canvas.addEventListener('pointermove',function(e){if(dragging)state.x=pointerPosition(e)});canvas.addEventListener('pointerup',function(){dragging=false});action.onclick=function(){state.auto=!state.auto;action.textContent='AUTO FIRE: '+(state.auto?'ON':'OFF')}}if(GAME==='doom'||GAME==='vampire'){document.querySelectorAll('[data-dir]').forEach(function(b){b.onclick=function(){var d=b.getAttribute('data-dir');move(d==='left'?-24:d==='right'?24:0,d==='up'?-24:d==='down'?24:0)}});action.onclick=fire}if(GAME==='cyber'){action.onclick=fire;el('jump').onclick=jump}}
start.onclick=reset;controls();document.addEventListener('keydown',function(e){if(e.key==='ArrowLeft')move(-24,0);if(e.key==='ArrowRight')move(24,0);if(e.key==='ArrowUp')move(0,-24);if(e.key==='ArrowDown')move(0,24);if(e.code==='Space'){if(GAME==='cyber')jump();else fire()}});draw();
})();`;
    const script = clientScript.replace('__GAME__', JSON.stringify(game)).replace('__ACCENT__', cfg.accent);
    return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>
*{box-sizing:border-box}html,body{margin:0;background:transparent;font-family:Arial,sans-serif}body{padding:6px;background:radial-gradient(circle at 50% 0%,#142333,#05070c 65%,#020305);color:#e9f7ff}.card{padding:12px;border:1px solid ${cfg.accent};border-radius:18px;background:linear-gradient(145deg,#0d1824,#071019 58%,#030509);box-shadow:0 0 18px ${cfg.accent}44,inset 0 0 0 1px #ffffff0b}.head{text-align:center}.kicker{color:${cfg.accent};font:9px monospace;letter-spacing:3px}.title{margin:3px 0;color:#fff;font:bold 24px Arial Black,Arial,sans-serif;letter-spacing:2px;text-shadow:0 0 8px ${cfg.accent},0 0 20px ${cfg.accent}88}.sub{color:#9bb4c7;font:9px monospace;letter-spacing:1px}.hud{display:flex;justify-content:space-between;gap:5px;margin:9px 0;padding:8px;border:1px solid ${cfg.accent}66;border-radius:9px;background:#02060b;color:#a7c4d3;font:9px monospace}.hud b{color:${cfg.accent};font-size:12px}.hud span{white-space:nowrap}.arena{position:relative;overflow:hidden;border:1px solid ${cfg.accent}99;border-radius:12px;background:#02070a;box-shadow:inset 0 0 25px ${cfg.accent}22}.arena canvas{display:block;width:100%;height:auto;image-rendering:auto}.overlay{position:absolute;inset:0;display:grid;place-items:center;background:#02060acc}.overlay.hide{display:none}.overlay button{min-width:145px;padding:11px;border:1px solid ${cfg.accent};border-radius:10px;background:#061b1e;color:${cfg.accent};font:bold 13px monospace;box-shadow:0 0 14px ${cfg.accent}66}.controls{display:flex;align-items:center;justify-content:center;gap:8px;margin-top:9px;min-height:62px}.controls button{min-width:100px;height:39px;border:1px solid ${cfg.accent};border-radius:9px;background:linear-gradient(#14303a,#07151d);color:${cfg.accent};font:bold 10px monospace;box-shadow:0 0 8px ${cfg.accent}33}.controls button:active{transform:scale(.94)}.dpad{display:grid;grid-template-columns:repeat(3,32px);gap:3px}.dpad button{min-width:32px;width:32px;height:28px;padding:0}.dpad button:first-child{grid-column:2}.dpad button:nth-child(2){grid-column:1;grid-row:2}.dpad button:nth-child(3){grid-column:2;grid-row:2}.dpad button:nth-child(4){grid-column:3;grid-row:2}.hint{text-align:center;margin-top:7px;color:#7390a2;font:9px monospace}.flash{animation:flash .22s}@keyframes flash{50%{filter:brightness(2.5)}}
</style></head><body><div class="card"><div class="head"><div class="kicker">SUKUNA ARCADE // GENAI</div><div class="title">${cfg.title}</div><div class="sub">${cfg.subtitle}</div></div><div class="hud">${cfg.hud}</div><div class="arena"><canvas id="game" width="320" height="400"></canvas><div class="overlay" id="overlay"><button id="start">START GAME</button></div></div><div class="controls">${cfg.controls}</div><div class="hint">${cfg.hint}</div></div><script>${script}</script></body></html>`;
}

async function sendArcade({ sock, msg, from, game }) {
    return sendRichHtml({ sock, jid: from, quoted: msg, html: arcadeHtml(game) });
}

module.exports = { arcadeHtml, sendArcade };
