'use strict';

// Original anime-inspired lines, not verbatim dialogue from the listed works.
const quotes = [
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Naruto Uzumaki', anime: 'Naruto' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Sasuke Uchiha', anime: 'Naruto' },
    { text: 'The road changes when you decide not to turn back.', character: 'Sakura Haruno', anime: 'Naruto' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Kakashi Hatake', anime: 'Naruto' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Itachi Uchiha', anime: 'Naruto' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Hinata Hyuga', anime: 'Naruto' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Shikamaru Nara', anime: 'Naruto' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Jiraiya', anime: 'Naruto' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Gaara', anime: 'Naruto' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Rock Lee', anime: 'Naruto' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Monkey D. Luffy', anime: 'One Piece' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Roronoa Zoro', anime: 'One Piece' },
    { text: 'The road changes when you decide not to turn back.', character: 'Nami', anime: 'One Piece' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Sanji', anime: 'One Piece' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Usopp', anime: 'One Piece' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Tony Tony Chopper', anime: 'One Piece' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Nico Robin', anime: 'One Piece' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Portgas D. Ace', anime: 'One Piece' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Trafalgar Law', anime: 'One Piece' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Shanks', anime: 'One Piece' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Goku', anime: 'Dragon Ball' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Vegeta', anime: 'Dragon Ball' },
    { text: 'The road changes when you decide not to turn back.', character: 'Gohan', anime: 'Dragon Ball' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Piccolo', anime: 'Dragon Ball' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Bulma', anime: 'Dragon Ball' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Trunks', anime: 'Dragon Ball' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Frieza', anime: 'Dragon Ball' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Krillin', anime: 'Dragon Ball' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Master Roshi', anime: 'Dragon Ball' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Android 18', anime: 'Dragon Ball' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Ichigo Kurosaki', anime: 'Bleach' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Rukia Kuchiki', anime: 'Bleach' },
    { text: 'The road changes when you decide not to turn back.', character: 'Byakuya Kuchiki', anime: 'Bleach' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Renji Abarai', anime: 'Bleach' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Kisuke Urahara', anime: 'Bleach' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Toshiro Hitsugaya', anime: 'Bleach' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Kenpachi Zaraki', anime: 'Bleach' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Orihime Inoue', anime: 'Bleach' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Yoruichi Shihōin', anime: 'Bleach' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Sosuke Aizen', anime: 'Bleach' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Eren Yeager', anime: 'Attack on Titan' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Mikasa Ackerman', anime: 'Attack on Titan' },
    { text: 'The road changes when you decide not to turn back.', character: 'Armin Arlert', anime: 'Attack on Titan' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Levi Ackerman', anime: 'Attack on Titan' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Erwin Smith', anime: 'Attack on Titan' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Hange Zoë', anime: 'Attack on Titan' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Historia Reiss', anime: 'Attack on Titan' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Reiner Braun', anime: 'Attack on Titan' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Annie Leonhart', anime: 'Attack on Titan' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Jean Kirstein', anime: 'Attack on Titan' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Tanjiro Kamado', anime: 'Demon Slayer' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Nezuko Kamado', anime: 'Demon Slayer' },
    { text: 'The road changes when you decide not to turn back.', character: 'Zenitsu Agatsuma', anime: 'Demon Slayer' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Inosuke Hashibira', anime: 'Demon Slayer' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Giyu Tomioka', anime: 'Demon Slayer' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Shinobu Kocho', anime: 'Demon Slayer' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Kyojuro Rengoku', anime: 'Demon Slayer' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Mitsuri Kanroji', anime: 'Demon Slayer' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Tengen Uzui', anime: 'Demon Slayer' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Muzan Kibutsuji', anime: 'Demon Slayer' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Yuji Itadori', anime: 'Jujutsu Kaisen' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Megumi Fushiguro', anime: 'Jujutsu Kaisen' },
    { text: 'The road changes when you decide not to turn back.', character: 'Nobara Kugisaki', anime: 'Jujutsu Kaisen' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Satoru Gojo', anime: 'Jujutsu Kaisen' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Ryomen Sukuna', anime: 'Jujutsu Kaisen' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Maki Zenin', anime: 'Jujutsu Kaisen' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Yuta Okkotsu', anime: 'Jujutsu Kaisen' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Toge Inumaki', anime: 'Jujutsu Kaisen' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Kento Nanami', anime: 'Jujutsu Kaisen' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Suguru Geto', anime: 'Jujutsu Kaisen' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Izuku Midoriya', anime: 'My Hero Academia' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Katsuki Bakugo', anime: 'My Hero Academia' },
    { text: 'The road changes when you decide not to turn back.', character: 'Shoto Todoroki', anime: 'My Hero Academia' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Ochaco Uraraka', anime: 'My Hero Academia' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'All Might', anime: 'My Hero Academia' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Tenya Iida', anime: 'My Hero Academia' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Eijiro Kirishima', anime: 'My Hero Academia' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Momo Yaoyorozu', anime: 'My Hero Academia' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Shota Aizawa', anime: 'My Hero Academia' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Tomura Shigaraki', anime: 'My Hero Academia' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Gon Freecss', anime: 'Hunter x Hunter' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Killua Zoldyck', anime: 'Hunter x Hunter' },
    { text: 'The road changes when you decide not to turn back.', character: 'Kurapika', anime: 'Hunter x Hunter' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Leorio Paradinight', anime: 'Hunter x Hunter' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Hisoka Morow', anime: 'Hunter x Hunter' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Chrollo Lucilfer', anime: 'Hunter x Hunter' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Meruem', anime: 'Hunter x Hunter' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Komugi', anime: 'Hunter x Hunter' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Biscuit Krueger', anime: 'Hunter x Hunter' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Isaac Netero', anime: 'Hunter x Hunter' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Edward Elric', anime: 'Fullmetal Alchemist' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Alphonse Elric', anime: 'Fullmetal Alchemist' },
    { text: 'The road changes when you decide not to turn back.', character: 'Winry Rockbell', anime: 'Fullmetal Alchemist' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Roy Mustang', anime: 'Fullmetal Alchemist' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Riza Hawkeye', anime: 'Fullmetal Alchemist' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Scar', anime: 'Fullmetal Alchemist' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Maes Hughes', anime: 'Fullmetal Alchemist' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Olivier Armstrong', anime: 'Fullmetal Alchemist' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Greed', anime: 'Fullmetal Alchemist' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Van Hohenheim', anime: 'Fullmetal Alchemist' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Light Yagami', anime: 'Death Note' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'L Lawliet', anime: 'Death Note' },
    { text: 'The road changes when you decide not to turn back.', character: 'Misa Amane', anime: 'Death Note' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Ryuk', anime: 'Death Note' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Near', anime: 'Death Note' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Mello', anime: 'Death Note' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Soichiro Yagami', anime: 'Death Note' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Rem', anime: 'Death Note' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Teru Mikami', anime: 'Death Note' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Watari', anime: 'Death Note' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Ken Kaneki', anime: 'Tokyo Ghoul' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Touka Kirishima', anime: 'Tokyo Ghoul' },
    { text: 'The road changes when you decide not to turn back.', character: 'Rize Kamishiro', anime: 'Tokyo Ghoul' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Hideyoshi Nagachika', anime: 'Tokyo Ghoul' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Kishou Arima', anime: 'Tokyo Ghoul' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Juuzou Suzuya', anime: 'Tokyo Ghoul' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Shuu Tsukiyama', anime: 'Tokyo Ghoul' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Eto Yoshimura', anime: 'Tokyo Ghoul' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Nishiki Nishio', anime: 'Tokyo Ghoul' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Koutarou Amon', anime: 'Tokyo Ghoul' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Kirito', anime: 'Sword Art Online' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Asuna Yuuki', anime: 'Sword Art Online' },
    { text: 'The road changes when you decide not to turn back.', character: 'Sinon', anime: 'Sword Art Online' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Eugeo', anime: 'Sword Art Online' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Alice Zuberg', anime: 'Sword Art Online' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Klein', anime: 'Sword Art Online' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Agil', anime: 'Sword Art Online' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Yui', anime: 'Sword Art Online' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Leafa', anime: 'Sword Art Online' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Heathcliff', anime: 'Sword Art Online' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Natsu Dragneel', anime: 'Fairy Tail' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Lucy Heartfilia', anime: 'Fairy Tail' },
    { text: 'The road changes when you decide not to turn back.', character: 'Gray Fullbuster', anime: 'Fairy Tail' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Erza Scarlet', anime: 'Fairy Tail' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Wendy Marvell', anime: 'Fairy Tail' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Happy', anime: 'Fairy Tail' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Gajeel Redfox', anime: 'Fairy Tail' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Juvia Lockser', anime: 'Fairy Tail' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Makarov Dreyar', anime: 'Fairy Tail' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Zeref Dragneel', anime: 'Fairy Tail' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Asta', anime: 'Black Clover' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Yuno', anime: 'Black Clover' },
    { text: 'The road changes when you decide not to turn back.', character: 'Noelle Silva', anime: 'Black Clover' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Yami Sukehiro', anime: 'Black Clover' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Mereoleona Vermillion', anime: 'Black Clover' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Luck Voltia', anime: 'Black Clover' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Finral Roulacase', anime: 'Black Clover' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Vanessa Enoteca', anime: 'Black Clover' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Julius Novachrono', anime: 'Black Clover' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Nacht Faust', anime: 'Black Clover' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Shoyo Hinata', anime: 'Haikyuu!!' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Tobio Kageyama', anime: 'Haikyuu!!' },
    { text: 'The road changes when you decide not to turn back.', character: 'Daichi Sawamura', anime: 'Haikyuu!!' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Koshi Sugawara', anime: 'Haikyuu!!' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Kei Tsukishima', anime: 'Haikyuu!!' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Toru Oikawa', anime: 'Haikyuu!!' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Kotaro Bokuto', anime: 'Haikyuu!!' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Kenma Kozume', anime: 'Haikyuu!!' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Tetsuro Kuroo', anime: 'Haikyuu!!' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Wakatoshi Ushijima', anime: 'Haikyuu!!' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Yoichi Isagi', anime: 'Blue Lock' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Meguru Bachira', anime: 'Blue Lock' },
    { text: 'The road changes when you decide not to turn back.', character: 'Rin Itoshi', anime: 'Blue Lock' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Seishiro Nagi', anime: 'Blue Lock' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Reo Mikage', anime: 'Blue Lock' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Ryusei Shidou', anime: 'Blue Lock' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Michael Kaiser', anime: 'Blue Lock' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Hyoma Chigiri', anime: 'Blue Lock' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Rensuke Kunigami', anime: 'Blue Lock' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Shoei Barou', anime: 'Blue Lock' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Denji', anime: 'Chainsaw Man' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Power', anime: 'Chainsaw Man' },
    { text: 'The road changes when you decide not to turn back.', character: 'Makima', anime: 'Chainsaw Man' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Aki Hayakawa', anime: 'Chainsaw Man' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Kobeni Higashiyama', anime: 'Chainsaw Man' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Himeno', anime: 'Chainsaw Man' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Kishibe', anime: 'Chainsaw Man' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Reze', anime: 'Chainsaw Man' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Angel Devil', anime: 'Chainsaw Man' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Beam', anime: 'Chainsaw Man' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Saitama', anime: 'One Punch Man' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Genos', anime: 'One Punch Man' },
    { text: 'The road changes when you decide not to turn back.', character: 'Tatsumaki', anime: 'One Punch Man' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Fubuki', anime: 'One Punch Man' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Garou', anime: 'One Punch Man' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'King', anime: 'One Punch Man' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Mumen Rider', anime: 'One Punch Man' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Bang', anime: 'One Punch Man' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Sonic', anime: 'One Punch Man' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Child Emperor', anime: 'One Punch Man' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Shigeo Kageyama', anime: 'Mob Psycho 100' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Arataka Reigen', anime: 'Mob Psycho 100' },
    { text: 'The road changes when you decide not to turn back.', character: 'Ritsu Kageyama', anime: 'Mob Psycho 100' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Teruki Hanazawa', anime: 'Mob Psycho 100' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Dimple', anime: 'Mob Psycho 100' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Tome Kurata', anime: 'Mob Psycho 100' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Musashi', anime: 'Mob Psycho 100' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Toichiro Suzuki', anime: 'Mob Psycho 100' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Sho Suzuki', anime: 'Mob Psycho 100' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Tenga Onigawara', anime: 'Mob Psycho 100' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Lelouch Lamperouge', anime: 'Code Geass' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'C.C.', anime: 'Code Geass' },
    { text: 'The road changes when you decide not to turn back.', character: 'Suzaku Kururugi', anime: 'Code Geass' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Nunnally vi Britannia', anime: 'Code Geass' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Kallen Stadtfeld', anime: 'Code Geass' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Charles zi Britannia', anime: 'Code Geass' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Shirley Fenette', anime: 'Code Geass' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Jeremiah Gottwald', anime: 'Code Geass' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Rolo Lamperouge', anime: 'Code Geass' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Milly Ashford', anime: 'Code Geass' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Rintaro Okabe', anime: 'Steins;Gate' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Kurisu Makise', anime: 'Steins;Gate' },
    { text: 'The road changes when you decide not to turn back.', character: 'Mayuri Shiina', anime: 'Steins;Gate' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Itaru Hashida', anime: 'Steins;Gate' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Suzuha Amane', anime: 'Steins;Gate' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Moeka Kiryu', anime: 'Steins;Gate' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Luka Urushibara', anime: 'Steins;Gate' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Faris Nyannyan', anime: 'Steins;Gate' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Katsumi Nakase', anime: 'Steins;Gate' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Yuugo Tennouji', anime: 'Steins;Gate' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Shinji Ikari', anime: 'Neon Genesis Evangelion' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Rei Ayanami', anime: 'Neon Genesis Evangelion' },
    { text: 'The road changes when you decide not to turn back.', character: 'Asuka Langley', anime: 'Neon Genesis Evangelion' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Misato Katsuragi', anime: 'Neon Genesis Evangelion' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Gendo Ikari', anime: 'Neon Genesis Evangelion' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Kaworu Nagisa', anime: 'Neon Genesis Evangelion' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Ritsuko Akagi', anime: 'Neon Genesis Evangelion' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Toji Suzuhara', anime: 'Neon Genesis Evangelion' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Hikari Horaki', anime: 'Neon Genesis Evangelion' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Pen Pen', anime: 'Neon Genesis Evangelion' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Usagi Tsukino', anime: 'Sailor Moon' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Ami Mizuno', anime: 'Sailor Moon' },
    { text: 'The road changes when you decide not to turn back.', character: 'Rei Hino', anime: 'Sailor Moon' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Makoto Kino', anime: 'Sailor Moon' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Minako Aino', anime: 'Sailor Moon' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Mamoru Chiba', anime: 'Sailor Moon' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Chibiusa', anime: 'Sailor Moon' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Setsuna Meioh', anime: 'Sailor Moon' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Haruka Tenoh', anime: 'Sailor Moon' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Michiru Kaioh', anime: 'Sailor Moon' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Inuyasha', anime: 'Inuyasha' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Kagome Higurashi', anime: 'Inuyasha' },
    { text: 'The road changes when you decide not to turn back.', character: 'Sesshomaru', anime: 'Inuyasha' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Miroku', anime: 'Inuyasha' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Sango', anime: 'Inuyasha' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Shippo', anime: 'Inuyasha' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Kikyo', anime: 'Inuyasha' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Naraku', anime: 'Inuyasha' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Koga', anime: 'Inuyasha' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Kaede', anime: 'Inuyasha' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Spike Spiegel', anime: 'Cowboy Bebop' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Jet Black', anime: 'Cowboy Bebop' },
    { text: 'The road changes when you decide not to turn back.', character: 'Faye Valentine', anime: 'Cowboy Bebop' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Edward Wong', anime: 'Cowboy Bebop' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Vicious', anime: 'Cowboy Bebop' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Julia', anime: 'Cowboy Bebop' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Ein', anime: 'Cowboy Bebop' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Gren', anime: 'Cowboy Bebop' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Annie', anime: 'Cowboy Bebop' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Laughing Bull', anime: 'Cowboy Bebop' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Mugen', anime: 'Samurai Champloo' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Jin', anime: 'Samurai Champloo' },
    { text: 'The road changes when you decide not to turn back.', character: 'Fuu Kasumi', anime: 'Samurai Champloo' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Kariya Kagetoki', anime: 'Samurai Champloo' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Sara', anime: 'Samurai Champloo' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Okuru', anime: 'Samurai Champloo' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Umanosuke', anime: 'Samurai Champloo' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Yatsuha', anime: 'Samurai Champloo' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Mukuro', anime: 'Samurai Champloo' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Koza', anime: 'Samurai Champloo' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Mitsuha Miyamizu', anime: 'Your Name' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Taki Tachibana', anime: 'Your Name' },
    { text: 'The road changes when you decide not to turn back.', character: 'Hitoha Miyamizu', anime: 'Your Name' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Yotsuha Miyamizu', anime: 'Your Name' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Tessie', anime: 'Your Name' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Sayaka Natori', anime: 'Your Name' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Tsukasa Fujii', anime: 'Your Name' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Miki Okudera', anime: 'Your Name' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Katsuhiko Teshigawara', anime: 'Your Name' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Yukari Yukino', anime: 'Your Name' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Chihiro Ogino', anime: 'Spirited Away' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Haku', anime: 'Spirited Away' },
    { text: 'The road changes when you decide not to turn back.', character: 'Yubaba', anime: 'Spirited Away' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Zeniba', anime: 'Spirited Away' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'No-Face', anime: 'Spirited Away' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Lin', anime: 'Spirited Away' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Kamaji', anime: 'Spirited Away' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Boh', anime: 'Spirited Away' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Akio Ogino', anime: 'Spirited Away' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Yuko Ogino', anime: 'Spirited Away' },
    { text: 'A heart that keeps moving can outwalk any shadow.', character: 'Sophie Hatter', anime: 'Howl’s Moving Castle' },
    { text: 'Courage is not noise; it is the choice made after fear arrives.', character: 'Howl Jenkins Pendragon', anime: 'Howl’s Moving Castle' },
    { text: 'The road changes when you decide not to turn back.', character: 'Calcifer', anime: 'Howl’s Moving Castle' },
    { text: 'Power means little until it protects someone beyond yourself.', character: 'Markl', anime: 'Howl’s Moving Castle' },
    { text: 'Even a broken dream can become the blueprint for a stronger one.', character: 'Witch of the Waste', anime: 'Howl’s Moving Castle' },
    { text: 'The hardest opponent is the voice that says you cannot rise.', character: 'Madame Suliman', anime: 'Howl’s Moving Castle' },
    { text: 'A promise becomes real when it survives the worst day.', character: 'Lettie Hatter', anime: 'Howl’s Moving Castle' },
    { text: 'Do not wait for destiny to open the door; build another entrance.', character: 'Martha Hatter', anime: 'Howl’s Moving Castle' },
    { text: 'Your scars are proof that the battle did not get the final word.', character: 'Honey Hatter', anime: 'Howl’s Moving Castle' },
    { text: 'When everything is lost, the will to begin again is still yours.', character: 'Turnip Head', anime: 'Howl’s Moving Castle' },
]

module.exports = {
    name: 'animequote',
    aliases: ['animequotes', 'aquote'],
    description: 'Get a random anime-inspired quote with its character and anime title',
    category: 'fun',
    async execute({ reply }) {
        const quote = quotes[Math.floor(Math.random() * quotes.length)];
        await reply(`🎌 *Anime Quote*\n\n_${quote.text}_\n\n— *${quote.character}*\n📺 _${quote.anime}_`);
    },
    quoteCount: quotes.length,
};
