'use strict';

const { sendRichHtml } = require('../../utils/genaiRich');

function tttHtml() {
    return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>
*{box-sizing:border-box}html,body{margin:0;background:transparent;font-family:Arial,sans-serif}body{padding:6px;background:radial-gradient(circle at 50% 4%,#143f5b,#07121f 74%)}.card{padding:13px;border:2px solid #4ec9ff;border-radius:20px;background:linear-gradient(145deg,#081d32,#123b53 52%,#071322);color:#d9f3ff;box-shadow:inset 0 0 0 3px #103958,0 8px 20px #000b}.title{text-align:center;color:#a9eaff;font:bold 23px Arial Black,Arial,sans-serif;letter-spacing:1px;text-shadow:0 0 11px #27c6ff}.sub{text-align:center;margin:2px 0 9px;color:#82bbd2;font:11px monospace}.score{display:flex;gap:6px;margin-bottom:8px}.score div{flex:1;padding:5px;border:1px solid #28678a;border-radius:8px;background:#061522;text-align:center;color:#74acc4;font:bold 9px monospace}.score b{display:block;margin-top:2px;color:#fff;font-size:16px}.board{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;padding:9px;border:2px solid #287eaa;border-radius:14px;background:#061622;box-shadow:inset 0 0 24px #000}.cell{height:72px;border:2px solid #1d6080;border-radius:11px;background:linear-gradient(145deg,#0b2636,#102e40);color:#f4fbff;font:bold 42px Arial;text-shadow:0 0 12px #43d6ff}.cell:active{transform:scale(.94)}.cell.x{color:#ff91cf;text-shadow:0 0 13px #ff2d9c}.cell.o{color:#72e9ff;text-shadow:0 0 13px #28ceff}.message{height:34px;margin:8px 0;display:grid;place-items:center;border:1px solid #2a7699;border-radius:8px;background:#06131f;color:#c9f4ff;font:bold 12px monospace}.buttons{display:grid;grid-template-columns:1fr 1fr;gap:7px}.buttons button{height:40px;border:2px solid #1d6e91;border-radius:11px;color:#e8fbff;background:linear-gradient(#185a79,#0b2d45);font-weight:900}.buttons button:active{transform:scale(.95)}#new{grid-column:1/-1;background:linear-gradient(#258ab3,#13506f)}.hint{text-align:center;margin:7px 0 0;color:#75a9bb;font:10px monospace}
</style></head><body><div class="card"><div class="title">❌ TIC-TAC-TOE ⭕</div><div class="sub">CHALLENGE THE CURSED AI · GET THREE IN A ROW</div><div class="score"><div>YOU<b id="you">0</b></div><div>DRAW<b id="draw">0</b></div><div>AI<b id="ai">0</b></div></div><div class="board" id="board"></div><div class="message" id="message">Your move — choose a square</div><div class="buttons"><button id="new">NEW ROUND</button><button id="mode">MODE: VS AI</button><button id="reset">RESET SCORE</button></div><div class="hint">Tap a square to place ❌ · the AI answers with ⭕</div></div><script>(function(){var board=document.getElementById('board'),msg=document.getElementById('message'),youEl=document.getElementById('you'),drawEl=document.getElementById('draw'),aiEl=document.getElementById('ai'),cells=Array(9).fill(''),turn='X',over=false,vsAI=true,scores={X:0,O:0,D:0},wins=[[0,1,2],[3,4,5],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];function draw(){board.innerHTML='';cells.forEach(function(v,i){var b=document.createElement('button');b.className='cell '+(v==='X'?'x':v==='O'?'o':'');b.textContent=v==='X'?'✕':v==='O'?'◯':'';b.onclick=function(){play(i)};board.appendChild(b)})}function result(){for(var i=0;i<wins.length;i++){var w=wins[i],a=cells[w[0]];if(a&&a===cells[w[1]]&&a===cells[w[2]])return a}return cells.every(Boolean)?'D':null}function finish(r){over=true;if(r==='X'){scores.X++;msg.textContent='YOU WIN — cursed technique mastered'}else if(r==='O'){scores.O++;msg.textContent='AI WINS — rematch the curse'}else{scores.D++;msg.textContent='DRAW — neither side breaks through'}youEl.textContent=scores.X;aiEl.textContent=scores.O;drawEl.textContent=scores.D;draw()}function aiMove(){if(over)return;var empty=cells.map(function(v,i){return v?null:i}).filter(function(v){return v!==null}),pick;if(empty.includes(4))pick=4;else{var best=-1;empty.forEach(function(i){cells[i]='O';var r=result(),value=r==='O'?10:r==='D'?0:1;cells[i]='';if(value>best){best=value;pick=i}})}cells[pick]='O';var r=result();if(r)finish(r);else{turn='X';msg.textContent='Your move — choose a square';draw()}}function play(i){if(over||cells[i]||turn!=='X')return;cells[i]='X';var r=result();if(r)return finish(r);if(vsAI){turn='O';msg.textContent='AI is thinking...';draw();setTimeout(aiMove,380)}else{turn='O';msg.textContent='⭕ turn — tap a square';draw()}}function newRound(){cells=Array(9).fill('');turn='X';over=false;msg.textContent='Your move — choose a square';draw()}document.getElementById('new').onclick=newRound;document.getElementById('mode').onclick=function(){vsAI=!vsAI;this.textContent='MODE: '+(vsAI?'VS AI':'2 PLAYER');newRound()};document.getElementById('reset').onclick=function(){scores={X:0,O:0,D:0};youEl.textContent='0';aiEl.textContent='0';drawEl.textContent='0';newRound()};draw()})();</script></body></html>`;
}

module.exports = {
    name: 'ttt',
    aliases: ['tictactoe', 'xo'],
    description: 'Play interactive Tic-Tac-Toe in WhatsApp GenAI',
    usage: '.ttt',
    category: 'games',
    async execute({ sock, msg, from, reply }) {
        try {
            await sendRichHtml({ sock, jid: from, quoted: msg, html: tttHtml() });
        } catch (error) {
            console.error('[TTT GenAI]', error.message);
            await reply('Tic-Tac-Toe could not open on this client. Please update WhatsApp or run `.ttt` again.');
        }
    },
};
